
services:
  ollama:
    image: ollama/ollama
    ports:
      - "${OLLAMA_HOST_PORT:-11434}:8000"  # Map external port (variable/11434) to internal 8000
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:8000  # Ollama serves on port 8000 inside container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/version"]  # Check internal port 8000
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama_data: